LIBRARY := SUHH2core
DICT := include/AnalysisModuleRunner.h include/NtupleObjects.h include/SUHH2core_LinkDef.h

USERLDFLAGS := -Wl,-rpath,/afs/desy.de/user/a/aggleton/public/fastjet/slc6_amd64_gcc530/fastjet-install/lib -lm -L/afs/desy.de/user/a/aggleton/public/fastjet/slc6_amd64_gcc530/fastjet-install/lib -lfastjettools -lfastjet -lHOTVR -lNsubjettiness -lRecursiveTools
USERCXXFLAGS := -I/afs/desy.de/user/a/aggleton/public/fastjet/slc6_amd64_gcc530/fastjet-install/include

TEST := 1
TESTPAR := 1
include ../Makefile.common
